import type { Metadata } from 'next'
import { Header } from '@/components/Header/Header'
import ThemeProvider from '@/components/ThemeProvider'

import { Inter } from 'next/font/google'

import { registerLanguage } from 'react-refractor'

import js from 'refractor/lang/javascript.js'
import jsx from 'refractor/lang/jsx'
import typescript from 'refractor/lang/typescript'

import './globals.css'
import '@/styles/prism.css'

registerLanguage(js)
registerLanguage(jsx)
registerLanguage(typescript)

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
