import type { Metadata } from 'next'
import ThemeProvider from '@/components/ThemeProvider'
import { RouterListener } from '@/components/RouterListener'
import { Noto_Sans } from 'next/font/google'
import { registerLanguage } from 'react-refractor'
import { GoogleOAuthProvider } from '@react-oauth/google'
import clsx from 'clsx'

import js from 'refractor/lang/javascript.js'
import jsx from 'refractor/lang/jsx'
import typescript from 'refractor/lang/typescript'

import Header from '@/components/Header'

import '@/styles/globals.css'
import '@/styles/prism.css'
import '@/styles/nprogress.css'

registerLanguage(js)
registerLanguage(jsx)
registerLanguage(typescript)

const font = Noto_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={clsx(font.className, 'font-light')}>
        <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID!}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <RouterListener />

            <Header />
            {children}

            <div className="hidden xl:block h-[100vh]"></div>
          </ThemeProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  )
}
